//package smthelusive.debyter.domain;
//
//public enum ResponseType {
//    RESPONSE_TYPE_NONE,
//    RESPONSE_TYPE_CLASS_INFO,
//    RESPONSE_TYPE_ALL_CLASSES,
//    RESPONSE_TYPE_COMPOSITE_EVENT,
//    RESPONSE_TYPE_EVENT_REQUEST,
//    RESPONSE_TYPE_METHODS,
//    RESPONSE_TYPE_LINETABLE,
//    RESPONSE_TYPE_VARIABLETABLE,
//    RESPONSE_TYPE_FRAME_INFO,
//    RESPONSE_TYPE_LOCAL_VARIABLES,
//    RESPONSE_TYPE_SINGLE_STEP,
//    RESPONSE_TYPE_ID_SIZES,
//    RESPONSE_TYPE_BYTECODES;
//
//}
